name: Build Python Image
run-name: ${{ github.actor }} Building Python Image
on: [push]
jobs:
  Build-Python-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Build Docker Image
        run: docker build --file Dockerfile -t beer-dataserver:$(date +%s) .

      - name: Save Docker image
        run: docker save --output beer_dataserver.tar beer-dataserver:$(date +%s)

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: python-image
          path: beer_dataserver.tar
          retention-days: 1